# Generated by Django 2.2.13 on 2021-07-21 18:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import osis_document.contrib.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0588_remove_learningcomponentyear_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100, verbose_name='Called from app')),
                ('model_name', models.CharField(max_length=100, verbose_name='Called from model name')),
                ('filters', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Filtres')),
                ('job_uuid', models.UUIDField(verbose_name='UUID of the related task job')),
                ('file', osis_document.contrib.fields.FileField(base_field=models.UUIDField(), default=list, null=True, size=None)),
                ('file_name', models.CharField(max_length=100, verbose_name='Nom de fichier')),
                ('type', models.CharField(choices=[('EXCEL', 'Excel'), ('PDF', 'PDF')], max_length=25, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Person')),
            ],
        ),
    ]
