# Generated by Django 3.2.20 on 2023-08-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_export', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Extra data'),
        ),
    ]
